# -*- coding: utf-8 -*-
"""Shared enum definitions for type safety and readability."""

from enum import Enum


class ReportType(str, Enum):
    """Report type used when API analysis triggers choose a report format."""

    SIMPLE = "simple"  # Compact report generated by generate_single_stock_report.
    FULL = "full"      # Full report generated by generate_dashboard_report.
    
    @classmethod
    def from_str(cls, value: str) -> "ReportType":
        """Convert a string safely to a ReportType, defaulting to SIMPLE."""
        try:
            return cls(value.lower().strip())
        except (ValueError, AttributeError):
            return cls.SIMPLE
    
    @property
    def display_name(self) -> str:
        """Return a user-facing display name."""
        return {
            ReportType.SIMPLE: "간단 리포트",
            ReportType.FULL: "상세 리포트",
        }.get(self, "간단 리포트")
